# Generated by Django 2.2.14 on 2021-05-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eleorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleorder',
            name='items',
        ),
        migrations.AddField(
            model_name='eleorder',
            name='item',
            field=models.ManyToManyField(to='core.EleOrderItem'),
        ),
    ]
