# Generated by Django 2.2.14 on 2021-05-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210502_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleorder',
            old_name='item',
            new_name='product',
        ),
    ]
