# Generated by Django 2.2.14 on 2021-05-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210502_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleorder',
            old_name='product',
            new_name='item',
        ),
    ]
