# Generated by Django 2.2.14 on 2021-05-04 18:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210502_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='eleorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='eleorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eleorderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='eleorderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=20, verbose_name=core.models.Category),
        ),
        migrations.DeleteModel(
            name='Electronics',
        ),
        migrations.DeleteModel(
            name='EleOrder',
        ),
        migrations.DeleteModel(
            name='EleOrderItem',
        ),
    ]
