# Generated by Django 2.2.14 on 2021-05-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210506_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='value',
            new_name='name',
        ),
    ]
