# Generated by Django 2.2.14 on 2021-05-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='item',
        ),
    ]
